name: cameratraps-classifier

channels:
- pytorch
- defaults

dependencies:
- python>=3.6

# from pytorch channel
- pytorch
- torchvision
- cpuonly  # for CPU only
# - cudatoolkit=10.2  # for GPU

# from defaults channel
- pandas
- nb_conda_kernels
- humanfriendly
- jupyterlab
- matplotlib
- mypy
- pillow
- pylint
- numpy
- openpyxl      # used by taxonomy_mapping/species_by_dataset.py
- progressbar2  # used by ai4eutils (which is called by taxonomy-mapping code)
- tqdm
- scikit-learn
- tensorboard
- pip
- xlrd          # for pandas Excel support, needed by taxonomy_mapping/process_species_by_dataset

# Some Azure packages or versions are only available from PyPI
# These may require GCC to be installed
- pip:
  - azure-cosmos
  - azure-storage-blob
